name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'input-output-hk/cardano-node'
      - name: delete all
        run: | 
          rm -rf ** && find . -name . -o -prune -exec rm -rf -- {} +

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start